// <auto-generated />
using System;
using BpMeasurementApp.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BpMeasurementApp.Migrations
{
    [DbContext(typeof(BpMeasurementDbContext))]
    [Migration("20241005010456_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BpMeasurementApp.Entities.BpMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diastolic = 80,
                            MeasurementDate = new DateTime(2024, 10, 4, 21, 4, 54, 634, DateTimeKind.Local).AddTicks(1630),
                            Systolic = 120
                        },
                        new
                        {
                            Id = 2,
                            Diastolic = 90,
                            MeasurementDate = new DateTime(2024, 10, 4, 21, 4, 54, 634, DateTimeKind.Local).AddTicks(1681),
                            Systolic = 100
                        },
                        new
                        {
                            Id = 3,
                            Diastolic = 80,
                            MeasurementDate = new DateTime(2024, 10, 4, 21, 4, 54, 634, DateTimeKind.Local).AddTicks(1684),
                            Systolic = 110
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
